version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: es7
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "transport.host=localhost"
      - "transport.tcp.port=9300"
      - "http.port=9200"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "network.host=0.0.0.0"
      - "reindex.remote.whitelist=host_to_whitelist:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
      - ./esconfig/synonym.txt:/usr/share/elasticsearch/config/synonym.txt
    ports:
      - 9200:9200
    dns:
      - 1.1.1.1
    extra_hosts:
      docker.for.lin.host.internal: 172.16.202.1
      docker.for.lin.localhost: 172.16.202.1
    networks:
      es7net:
        ipv4_address: 172.16.202.2

  cerebro:
    image: lmenezes/cerebro:0.8.1
    container_name: cerebro_es7
    ports:
      - 9000:9000
    depends_on:
      - elasticsearch
    dns:
      - 1.1.1.1
    extra_hosts:
      docker.for.lin.host.internal: 172.16.202.2
      docker.for.lin.localhost: 172.16.202.2
    networks:
      es7net:
        ipv4_address: 172.16.202.3

  kibana:
      image: docker.elastic.co/kibana/kibana:7.9.2
      container_name: kibana_es7
      volumes:
        - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      environment:
        MONITORING_ENABLED: "false"
      ports:
        - 5601:5601
      depends_on:
        - elasticsearch
      dns:
        - 1.1.1.1
      extra_hosts:
        docker.for.lin.host.internal: 172.16.202.3
        docker.for.lin.localhost: 172.16.202.3
      networks:
        es7net:
          ipv4_address: 172.16.202.4

networks:
  es7net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.202.0/24
          gateway: 172.16.202.1
